# Site settings
baseurl = "http://danielpfeiffer.me"
publishDir = "docs"
themesDir = "./themes/"
languageCode = "en-us"
title = "Daniel Pfeiffer - Software Engineer"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = "danielpfeiffer"

[params]
	name = "Daniel Pfeiffer"
	description = "asdfasdfasdfa asdfasdfas"
	bio = "Software Engineer"
	# Enter optionally your twitter account
	twitter = "pfeiffer_d_"
	enableRSS = false

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Software Engineer at Firstbird"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "rounded"

# Add additional social link entries underneath
[social]
    twitter  = "https://twitter.com/pfeiffer_d_"
    # facebook = "https://www.facebook.com/"
    github   = "https://github.com/dpfeiffer"
    linkedin  = "https://www.linkedin.com/in/danielpfeifferat/"
